import React, { useEffect, useState } from 'react';
import { Menu, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { auth } from '../firebase';
import { onAuthStateChanged } from 'firebase/auth';
import BrandMark from './BrandMark';
import './Landing.css';
const links = ['Home', 'About', 'Services', 'Team', 'Projects', 'Contact'];
const Navbar = () => { const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const [user, setUser] = useState(null); const navigate = useNavigate(); useEffect(() => { const listener = () => setScrolled(window.scrollY > 16); window.addEventListener('scroll', listener); return () => window.removeEventListener('scroll', listener); }, []); useEffect(() => onAuthStateChanged(auth, setUser), []); const go = id => { document.getElementById(id.toLowerCase())?.scrollIntoView({ behavior: 'smooth' }); setOpen(false); }; return <nav className={`navbar-simple ${scrolled ? 'is-scrolled' : ''}`}><div className="page-shell nav-inner"><button className="brand" onClick={() => go('home')} aria-label="Craftelligence home"><BrandMark /><span>craftelligence<small>We build. You scale.</small></span></button><div className={`nav-links ${open ? 'is-open' : ''}`}>{links.map(link => <button key={link} onClick={() => go(link)}>{link}</button>)}<button className="nav-cta" onClick={() => user ? navigate('/profile') : navigate('/developer-registration')}>{user ? 'My profile' : 'Join our team'}</button></div><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X size={21} /> : <Menu size={22} />}</button></div></nav> };
export default Navbar;
