import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowLeft, ArrowRight, Quote } from 'lucide-react';
import './Landing.css';
const items = [
  ['Krishna Kumar', 'Founder, EvidenceMD.ai', 'Craftelligence built our entire platform—backend, frontend, and AI integration—with unmatched precision. Their LLM expertise made our medical assistant accurate and reliable for real-world clinicians.'],
  ['Olivia Harris', 'Director, AU Legal Docs', 'Their team delivered a secure, automated system for legal documentation. From AWS integration to payment workflows, everything runs seamlessly—truly production-grade engineering.'],
  ['Michael Reed', 'Co-Founder, Community 365', 'Craftelligence turned our vision for a community safety app into reality. Their technical depth in mobile, API, and real-time systems gave us a reliable and fast-performing platform.'],
  ['Sarah Patel', 'CTO, Asper AI', 'They developed our ontology and data harmonization engine with remarkable insight. Their work in LLMs, Neo4j, and automation set new standards for our internal AI workflows.']
];
const Testimonials = () => { const [index, setIndex] = useState(0); useEffect(() => { const timer = setInterval(() => setIndex(i => (i + 1) % items.length), 6500); return () => clearInterval(timer); }, []); const [name, role, quote] = items[index]; return <section id="testimonials" className="clean-section testimonials"><div className="page-shell testimonial-layout"><div><span className="eyebrow">Kind words</span><h2>Good work makes a difference people can feel.</h2><div className="testimonial-controls"><button onClick={() => setIndex(i => (i - 1 + items.length) % items.length)} aria-label="Previous testimonial"><ArrowLeft size={19} /></button><button onClick={() => setIndex(i => (i + 1) % items.length)} aria-label="Next testimonial"><ArrowRight size={19} /></button><span>{String(index + 1).padStart(2, '0')} / {String(items.length).padStart(2, '0')}</span></div></div><div className="quote-wrap"><AnimatePresence mode="wait"><motion.figure key={name} className="quote-card" initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -15 }} transition={{ duration: .35 }}><Quote className="quote-mark" size={34} /><blockquote>“{quote}”</blockquote><figcaption><span>{name.slice(0, 1)}</span><div><strong>{name}</strong><small>{role}</small></div></figcaption></motion.figure></AnimatePresence></div></div></section> };
export default Testimonials;
